import { useLocation, useNavigate } from "react-router-dom";
import {
    InputOTP,
    InputOTPGroup,
    InputOTPSeparator,
    InputOTPSlot,
} from "@/components/ui/input-otp"
import { Button } from "@/components/ui/button";
import { Link } from "react-router-dom";
import { useState } from "react";
import { useAppDispatch } from "@/stores/hooks";
import { verifyMfa } from "@/stores/slices/authSlice";

export default function VerifyMfa() {
    const { state } = useLocation();
    const {  secretImageUri,email } = state;
    const [code,setCode] = useState('')
    const dispatch = useAppDispatch();
    const navigate = useNavigate();
    

   const handleVerifyMfa = () => {
    dispatch(verifyMfa({
        code,
        email,
        navigate
    }))
   }

    return (
        <div className="flex-center flex-col h-screen ">
            <div className="background-light900_dark300 rounded-lg max-w-[550px]  p-6 flex-col flex shadow-lg  max-sm:mx-4">
                <h1 className="h2-bold border-b pb-2 border-light-2 ">Verify MFA</h1>
                <div className="flex-center my-4"><img src={secretImageUri} alt="QR code" className="size-[180px] " /></div>
                <div className="flex gap-5 flex-col mb-5">
                    <p className="flex  gap-4 text-light-400 paragraph-regular"><span className="rounded-full bg-gray-300 text-dark-300 body-medium size-8  inline-flex items-center justify-center shrink-0">1</span>
                        Scan the QR code using any authentication application on your phone(e.g Google Authenticator, Microsoft Authenticator, Authy, etc.)</p>
                    <p className="flex  gap-4 text-light-400 paragraph-regular "><span className="rounded-full bg-gray-300 text-dark-300 body-medium size-8  inline-flex items-center justify-center ">2</span>
                        Enter the 6-digit code generated by the authentication
                    </p>
                </div>
                <div className="flex-center">
                    <InputOTP maxLength={6}
                    value={code}
                    onChange={(value) => setCode(value)}
                    autoFocus
                    >
                        <InputOTPGroup>
                            <InputOTPSlot index={0} />
                            <InputOTPSlot index={1} />
                            <InputOTPSlot index={2} />
                        </InputOTPGroup>
                        <InputOTPSeparator />
                        <InputOTPGroup>
                            <InputOTPSlot index={3} />
                            <InputOTPSlot index={4} />
                            <InputOTPSlot index={5} />
                        </InputOTPGroup>
                    </InputOTP>

                </div>

                <div className="flex justify-end gap-4 mt-5">
                    <Button variant={"ghost"}><Link to='/auth/login'>Cancel</Link></Button>
                    <Button className="text-white bg-primary-500 hover:opacity-100 opacity-90 min-w-[110px]"
                    onClick={handleVerifyMfa}
                    >Confirm</Button>
                </div>
            </div>
        </div>
    )
}