spring:
  application:
    name: queueoverflow
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 10MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 805570222142-ruqi6hhiit4dcaka9pmlfdb2iu3kfedi.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
#          facebook:
#            clientId: 1106813467180481
#            clientSecret: 7ffa2355ccf06f28aee9c121909e45c7
#            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
#            scope:
#              - email
#              - public_profile
          github:
            clientId: Iv23ligkDN0nZfgoi5HE
            clientSecret: 1dcce0ff2e60c015efe37a61b6cd7bd3835a62bb
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - user:email
              - read:user
#        provider:
#          facebook:
#            authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
#            tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
#            userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,picture



app:
  secure:
    jwt:
      secret-key: MHQCAQEEIEYgBlyQVsH7SpHUH7x4RErcckhu7ary/JjhP72Nk19EoAcGBSuBBAAKoUQDQgAE1MtHIxlGP5TARqBccrddNm1FnYH1Fp+onETz5KbXPSeG5FGwKMUXGfAmSZJq2gENULFewwymt+9bTXkjBZhh8A==
      token-expire: 86400000
      refreshToken-expire: 604800000
  ai:
    gpt-secret-key: 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

