spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stackoverflow
    username: root
    password: nam123456
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true


app:
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect

