spring:
  datasource:
    url: jdbc:mysql://viaduct.proxy.rlwy.net:48697/queueoverflow
    username: root
    password: KpOZlzLhKNdNgAdgMNVBobMJcyEZpjJo
  jpa:
    show-sql: false

app:
  oauth2:
    authorizedRedirectUris:
      - https://queue-overflow-g0d20y8mu-nemisolvs-projects.vercel.app/oauth2/redirect

